In [20]:
import numpy as np
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8]

ls = np.array(my_list).reshape(3,3)

In [21]:
print(ls)
print()
print(f'row_mean = {ls.mean(axis = 0)}')
print()
print(f'column_mean = {ls.mean(axis = 1)}')
print()
print(f'flat_mean = {ls.mean()}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

row_mean = [3. 4. 5.]

column_mean = [1. 4. 7.]

flat_mean = 4.0


In [22]:
print(ls)
print()
print(f'row_variance = {ls.var(axis = 0)}')
print()
print(f'column_variance = {ls.var(axis = 1)}')
print()
print(f'flat_variance = {ls.var()}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

row_variance = [6. 6. 6.]

column_variance = [0.66666667 0.66666667 0.66666667]

flat_variance = 6.666666666666667


In [23]:
print(ls)
print()
print(f'row_standard_deviation = {ls.std(axis = 0)}')
print()
print(f'column_standard_deviation = {ls.std(axis = 1)}')
print()
print(f'flat_standard_deviation = {ls.std()}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

row_standard_deviation = [2.44948974 2.44948974 2.44948974]

column_standard_deviation = [0.81649658 0.81649658 0.81649658]

flat_standard_deviation = 2.581988897471611


In [24]:
print(ls)
print()
print(f'row_max = {ls.max(axis = 0)}')
print()
print(f'column_max = {ls.max(axis = 1)}')
print()
print(f'flat_max = {ls.max()}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

row_max = [6 7 8]

column_max = [2 5 8]

flat_max = 8


In [25]:
print(ls)
print()
print(f'row_min = {ls.min(axis = 0)}')
print()
print(f'column_min = {ls.min(axis = 1)}')
print()
print(f'flat_min = {ls.min()}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

row_min = [0 1 2]

column_min = [0 3 6]

flat_min = 0


In [26]:
print(ls)
print()
print(f'row_sum = {ls.sum(axis = 0)}')
print()
print(f'column_sum = {ls.sum(axis = 1)}')
print()
print(f'flat_sum = {ls.sum()}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

row_sum = [ 9 12 15]

column_sum = [ 3 12 21]

flat_sum = 36


In [28]:
# FINAL BOSS

def calculate():
    ls = np.array(my_list).reshape(3,3)
    print(ls)
    
    # mean
    row_mean = ls.mean(axis = 0).tolist()
    column_mean = ls.mean(axis = 1).tolist()
    flat_mean = ls.mean().tolist()

    # variance
    row_variance = ls.var(axis = 0).tolist()
    column_variance = ls.var(axis = 1).tolist()
    flat_variance = ls.var().tolist()

    # standard deviation
    row_std = ls.std(axis = 0).tolist()
    column_std = ls.std(axis = 1).tolist()
    flat_std = ls.std().tolist()

    # maximum
    row_max = ls.max(axis = 0).tolist()
    column_max = ls.max(axis = 1).tolist()
    flat_max = ls.max().tolist()

    # minimum
    row_min = ls.min(axis = 0).tolist()
    column_min = ls.min(axis = 1).tolist()
    flat_min = ls.min().tolist()

    # summation
    row_sum = ls.sum(axis = 0).tolist()
    column_sum = ls.sum(axis = 1).tolist()
    flat_sum = ls.sum().tolist()
    
    return {
        'mean': [row_mean, column_mean, flat_mean],
  'variance': [row_variance, column_variance, flat_variance],
  'standard deviation': [row_std, column_std, flat_std],
  'max': [row_max, column_max, flat_max],
  'min': [row_min, column_min, flat_min],
  'sum': [row_sum, column_sum, flat_sum]
    }


calculate()

[[0 1 2]
 [3 4 5]
 [6 7 8]]


{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}